name: mention_kadohyo
on: workflow_dispatch
  
#  schedule:
#    # 定期実行する時間・・・①
#    - cron: '45 7 * * *'

defaults:
  run:
    working-directory: .github/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13.3
        uses: actions/setup-python@v1
        with:
          python-version: 3.13.3
      - name: Install dependencies
        run: |
        
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          python -m pip install -r requirements.txt
          
      - name: Run script
        env:
          API_KEY: ${{ secrets.WEBHOOK_URL }}
        run: |
          
          python MentionToWriteKadohyo.py
